### ISSUE TITLE
npm start throws error

### ISSUE THREAD

**Issue by Naveen7892** [PushpinderSinghGrewal/twitter-clone-hpdf-task-1#1]
![hpdf_clone_error_twitter_app_task1](https://user-images.githubusercontent.com/17492097/34454433-7737ea94-ed91-11e7-8005-612c58092bf6.PNG)

My system info:
OS: Windows 8.1

>$npm -v
4.6.1

>$node -v
v5.0.0

>$react-native -v
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

**Comment by PushpinderSinghGrewal** [comment]
This is a React.js project and not a React-native project. Please follow the steps mentioned in the readme file and then try to run the app using npm start. If you still can't then post the issue here.

**Comment by PushpinderSinghGrewal** [comment]
Also you should  have React.js on your system in order to run the project. If you dont have then follow the instructions here (http://www.react.express/environment)  to setup. I would recommend using create-react-app since it is fairly easy to setup.

**Comment by PushpinderSinghGrewal** [comment]
Please respond if you are facing any problem while running it in the React.js environmemt. I am going to close the issue otherwise.
